// One anchor space for the whole vault.
//
// A markdown heading and a LaTeX `\label` are the same kind of thing — a named
// place inside a note — so `[[Note#anchor]]` and `\ref{Note#anchor}` are one
// lookup, and neither the backlinks panel, the graph, the hover preview nor
// the outline has to know which format it is pointing at. Transclusion falls
// out of it for free: `![[Paper#eq:fourier]]` is "resolve the note, then
// resolve the anchor inside it", exactly as `![[Notes#Derivation]]` is.

// THE ANCHOR TABLE AND THE OUTLINE MUST AGREE ABOUT WHERE THE CODE IS. Both
// read `shared/fences.ts`; this file used to carry its own copy of the same
// marker-blind toggle, which meant a `### ` inside a ```markdown block that
// shows a `~~~` block became an addressable anchor the reading view never
// assigns an id to — a `[[Note#…]]` that silently misses, and a transclusion
// that pulls the wrong span.
import { isBareBlockId, parseBlockId, stripBlockId } from "./blockId.ts";
import { closesFence, fenceOpener, sourceLines, type Fence } from "./fences.ts";
import { isTexPath } from "./noteFormat.ts";
import { findAnchor, parseTex, slugAnchor, type NoteAnchor } from "./tex.ts";

export type { NoteAnchor } from "./tex.ts";
export { findAnchor, slugAnchor } from "./tex.ts";

const HEADING_RE = /^(#{1,6})\s+(.*)$/;

/** Inline markdown removed from a heading, for display and for slugging. Kept
 *  in step with client/reading/toc.ts's stripInline — that one feeds the TOC,
 *  this one feeds the anchor table, and an anchor whose id disagrees with the
 *  element id the reading view assigns is an anchor that silently misses. */
function stripInline(text: string): string {
  return text
    .replace(/!\[\[([^[\]]+?)\]\]/g, "$1")
    .replace(/\[\[([^\]|]+?)(?:\|([^\]]+))?\]\]/g, (_m, t: string, a?: string) => (a ?? t).trim())
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*|__|~~|==/g, "")
    .replace(/(^|\s)[*_]|[*_](\s|$)/g, "$1$2")
    .replace(/\s+#+\s*$/, "")
    .trim();
}

/** Every addressable place in a markdown note: its headings. Slugs collide the
 *  same way the reading view's do (`intro`, `intro-1`, …), because they are
 *  generated by the same rule in the same document order. */
export function markdownAnchors(md: string): NoteAnchor[] {
  const out: NoteAnchor[] = [];
  const seen = new Map<string, number>();
  const lines = sourceLines(md);
  let start = 0;
  if (lines[0]?.trim() === "---") {
    for (let j = 1; j < lines.length; j++) {
      const t = lines[j].trim();
      if (t === "---" || t === "...") {
        start = j + 1;
        break;
      }
    }
  }
  let fence: Fence | null = null;
  for (let i = start; i < lines.length; i++) {
    const line = lines[i];
    if (fence) {
      if (closesFence(line, fence)) fence = null;
      continue;
    }
    const opened = fenceOpener(line);
    if (opened) {
      fence = opened;
      continue;
    }
    const m = HEADING_RE.exec(line);
    if (m) {
      const text = stripInline(m[2]);
      const base = slugAnchor(text);
      const n = seen.get(base) ?? 0;
      seen.set(base, n + 1);
      out.push({ id: n === 0 ? base : `${base}-${n}`, kind: "heading", title: text, line: i + 1 });
      continue;
    }
    // A block id (shared/blockId.ts): ` ^id` at the end of a paragraph or a
    // list item, or on a line of its own under the block. The anchor's id
    // KEEPS the caret — `[[Note#^id]]` parses to the anchor "^id", and
    // findAnchor's first pass is the exact id — and its line is the line the
    // marker is on, which is the block's LAST line (blockRange walks up).
    // First one wins on a duplicate, as findAnchor's loop does.
    const block = parseBlockId(line);
    // Resolution lowercases (findAnchor), so `^Abc` and `^abc` are one id:
    // the first spelling wins, as it does for a duplicate heading slug.
    if (block && !seen.has(`^${block.id.toLowerCase()}`)) {
      seen.set(`^${block.id.toLowerCase()}`, 1);
      const own = isBareBlockId(line) ? (lines[i - 1] ?? "") : line;
      const title = stripInline(stripBlockId(own).replace(/^\s*(?:[-*+]|\d+[.)])\s+(?:\[[ xX]\]\s*)?/, "")).trim();
      out.push({ id: `^${block.id}`, kind: "block", title: title.length > 80 ? `${title.slice(0, 79)}…` : title, line: i + 1 });
    }
  }
  return out;
}

/** The anchor table for a note of EITHER format — the one function every
 *  cross-format feature calls. `.tex` notes are parsed; markdown notes are
 *  scanned for headings. */
export function noteAnchors(relPath: string, content: string): NoteAnchor[] {
  if (!isTexPath(relPath)) return markdownAnchors(content);
  return parseTex(content).anchors;
}

/** Resolve `#anchor` inside a note's content, whatever the note's format.
 *  Returns null for a miss — every caller renders that quietly, never as an
 *  error and never as raw source. */
export function resolveAnchorIn(
  relPath: string,
  content: string,
  anchor: string,
): NoteAnchor | null {
  return findAnchor(noteAnchors(relPath, content), anchor);
}

/** The 1-based source line an `#anchor` sits on in a note of either format —
 *  what the editor scrolls to when a `[[Note#anchor]]` is followed. null when
 *  the anchor does not resolve, which every caller treats as "just open the
 *  note", never as an error. */
export function anchorLine(relPath: string, content: string, anchor: string): number | null {
  return findAnchor(noteAnchors(relPath, content), anchor)?.line ?? null;
}
