// The kanji readings table, and what the furigana doors do with it.
//
// Split from shared/furigana.ts on purpose: that file is the PARSER, and the
// reading view, the outline and the live preview import it — it is in the
// closure every reader pays for. This file is the SUGGESTIONS, reached only
// from the editor's furigana door (client/editor/furigana.ts) and the popover
// behind it, and it should stay that way: a byte here is a byte a blog
// visitor never downloads. The table itself (shared/data/kanjiReadings.json,
// from KANJIDIC2 — the generator carries the EDRDG attribution) is a lazy
// chunk behind a dynamic import; this is the code that reads it.

import { findFurigana, isKana, isKanji, serialiseFurigana } from "./furigana.ts";

/** One kanji's readings: kun'yomi (the native readings, okurigana dropped)
 *  and on'yomi (the Sino-Japanese ones, written in hiragana), each most
 *  common first as KANJIDIC2 orders them; `x`, when present, lists per kun
 *  reading the okurigana KANJIDIC wrote after it (た → べる for 食), which is
 *  what lets 食べる be told from 食う. shared/data/kanjiReadings.json,
 *  generated by scripts/gen-kanji-readings.mjs. */
export interface KanjiReadings {
  k: string[];
  o: string[];
  x?: string[][];
}

export type ReadingsTable = Readonly<Record<string, KanjiReadings>>;

/** The suggestions for the kanji at `index` inside `run`, a run being the
 *  consecutive kanji of one word, and `after` the text that follows the run.
 *
 *  THE ORDER IS THE WHOLE VALUE OF A SUGGESTION. A compound of two or more
 *  kanji (漢字, 日本, 学校) is read with on'yomi far more often than not, so
 *  on comes first there; a single kanji with kana after it (食べる, 読む) is
 *  a native verb or adjective and reads with kun'yomi — and among the kun
 *  readings, the one whose okurigana the following kana actually continue
 *  (食 before べる is た, before う is く) goes to the very front. A single
 *  kanji on its own (山, 人) is likelier a native word too. Nothing here is
 *  a dictionary lookup of the word — the popover says so — it is the reading
 *  most likely to be the one wanted, put first so Enter is usually enough. */
export function suggestReadings(run: string, index: number, table: ReadingsTable, after = ""): string[] {
  const chars = [...run];
  const kanji = chars[index];
  if (kanji === undefined) return [];
  const entry = table[kanji];
  if (!entry) return [];
  const compound = chars.length >= 2;
  let kun = entry.k;
  // The last kanji of a run followed by kana: the reading whose okurigana
  // the kana continue is the reading. Scored by the longest shared prefix,
  // because the text is inflected (食べた, 食べ物) while KANJIDIC lists the
  // dictionary form (た.べる) — one kana in common is already the answer,
  // and more of them outranks fewer (上げる: あ.げる over のぼ.る).
  if (index === chars.length - 1 && entry.x && after !== "" && isKana(after[0])) {
    const score = (i: number): number =>
      Math.max(0, ...(entry.x?.[i] ?? []).map((tail) => sharedPrefix(tail, after)));
    const ranked = kun.map((r, i) => ({ r, i, s: score(i) }));
    ranked.sort((a, b) => b.s - a.s || a.i - b.i);
    kun = ranked.map((e) => e.r);
  }
  const first = compound ? entry.o : kun;
  const second = compound ? kun : entry.o;
  const seen = new Set<string>();
  const out: string[] = [];
  for (const r of [...first, ...second]) {
    if (r !== "" && !seen.has(r)) {
      seen.add(r);
      out.push(r);
    }
  }
  return out;
}

function sharedPrefix(a: string, b: string): number {
  let n = 0;
  while (n < a.length && n < b.length && a[n] === b[n]) n++;
  return n;
}

/** A run of consecutive kanji inside `text` — kana, spaces and punctuation
 *  break runs, so 食べ物 is two runs and 漢字 is one — with the text that
 *  follows it, which is what tells 食べる from 食う. Offsets are UTF-16
 *  units, which is what an editor range is made of. */
export interface KanjiRun {
  start: number;
  end: number;
  text: string;
  after: string;
}

export function kanjiRuns(text: string): KanjiRun[] {
  const out: KanjiRun[] = [];
  let i = 0;
  const chars = [...text];
  let pos = 0;
  while (i < chars.length) {
    if (isKanji(chars[i])) {
      const start = pos;
      let run = "";
      while (i < chars.length && isKanji(chars[i])) {
        run += chars[i];
        pos += chars[i].length;
        i++;
      }
      out.push({ start, end: pos, text: run, after: chars.slice(i, i + 4).join("") });
    } else {
      pos += chars[i].length;
      i++;
    }
  }
  return out;
}

/** The first suggestion for every kanji of a run, or null when any kanji is
 *  unknown to the table — half a reading over a word is worse than none. */
export function firstReadings(run: KanjiRun, table: ReadingsTable): string[] | null {
  const out: string[] = [];
  const chars = [...run.text];
  for (let i = 0; i < chars.length; i++) {
    const s = suggestReadings(run.text, i, table, run.after);
    if (s.length === 0) return null;
    out.push(s[0]);
  }
  return out;
}

/** Wrap every kanji run of `text` that is not already inside a furigana span
 *  in its first-suggestion reading — the "automatic" mode. Runs the table
 *  does not fully know are left as they were; the count says how many were
 *  written, so the caller can say "nothing to do" honestly. A run of two or
 *  more kanji takes ONE reading for the word (`{漢字|かんじ}`), which is how
 *  the compound reads and the shape the plugin's own examples use.
 *
 *  `range` limits the runs that are wrapped to those inside it while the
 *  whole of `text` stays in view: the editor passes a line and the selected
 *  part of it, so a run the selection ends on still sees the kana after it
 *  and 食 before べる is still た. */
export function autoFurigana(
  text: string,
  table: ReadingsTable,
  range: { from: number; to: number } = { from: 0, to: text.length },
): { text: string; count: number } {
  const taken = findFurigana(text);
  const inside = (from: number, to: number): boolean => taken.some((s) => from < s.end && to > s.start);
  let out = "";
  let at = 0;
  let count = 0;
  for (const run of kanjiRuns(text)) {
    if (run.start < range.from || run.end > range.to) continue;
    if (inside(run.start, run.end)) continue;
    const readings = firstReadings(run, table);
    if (readings === null) continue;
    out += text.slice(at, run.start) + serialiseFurigana(run.text, [readings.join("")]);
    at = run.end;
    count++;
  }
  return { text: out + text.slice(at), count };
}

/** Katakana → hiragana, for on'yomi that KANJIDIC2 lists in katakana: the
 *  two syllabaries sit 0x60 apart in Unicode for every voiced and unvoiced
 *  syllable, and the prolonged-sound mark ー has no hiragana twin and stays. */
export function toHiragana(s: string): string {
  let out = "";
  for (const ch of s) {
    const cp = ch.codePointAt(0) ?? 0;
    out += cp >= 0x30a1 && cp <= 0x30f6 ? String.fromCodePoint(cp - 0x60) : ch;
  }
  return out;
}
